framework/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings

import courses.views as courses_view


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include('courses.urls',namespace="courses")),
    url(r'^search/', include('haystack.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$',courses_view.indexView,name="index"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^$',views.ucIndex,name="uc_index"),
    url(r'^profile/',views.ucProfile,name="uc_profile"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    nickname = models.CharField("昵称",max_length=50, blank=True)
    bio = models.TextField("个人介绍",blank=True)
    website = models.URLField("网站地址",help_text="粘贴您的网站链接至此",blank=True)
    github = models.URLField("Github 地址",help_text="粘贴您的个人页面链接至此",blank=True)
    weibo = models.URLField("微博地址",help_text="粘贴您的微博至此",blank=True)
    class Meta(AbstractUser.Meta):
        pass

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

from django.forms import ModelForm


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")
class ProfileForm(ModelForm):
    class Meta:
        model = User
        fields = ['nickname','bio','website','github','weibo']

users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, ProfileForm
from .models import User


def register(request):
    # todo 处理 next 的安全性
    # 从 get 或者 post 请求中获取 next 参数值
    # get 请求中，next 通过 url 传递，即 /?next=value
    # post 请求中，next 通过表单传递，即 <input type="hidden" name="next" value="{{ next }}"/>
    redirect_to = request.POST.get('next', request.GET.get('next', ''))

    # 只有当请求为 POST 时，才表示用户提交了注册信息
    if request.method == 'POST':
        # request.POST 是一个类字典数据结构，记录了用户提交的注册信息
        # 这里提交的就是用户名（username）、密码（password）、确认密码、邮箱（email）
        # 用这些数据实例化一个用户注册表单
        form = RegisterForm(request.POST)

        # 验证数据的合法性
        if form.is_valid():
            # 如果提交数据合法，调用表单的 save 方法将用户数据保存到数据库
            form.save()

            if redirect_to:
                return redirect(redirect_to)
            else:
                return redirect('/')
    else:
        # 请求不是 POST，表明用户正在访问注册页面，展示一个空的注册表单给用户
        form = RegisterForm()

    # 渲染模板
    # 如果用户正在访问注册页面，则渲染的是一个空的注册表单
    # 如果用户通过表单提交注册信息，但是数据验证不合法，则渲染的是一个带有错误信息的表单
    # 将记录用户注册前页面的 redirect_to 传给模板，以维持 next 参数在整个注册流程中的传递
    return render(request, 'users/register.html', context={'form': form, 'next': redirect_to})


def ucIndex(request):
    return render(request, "usercenter/index.html")


def ucProfile(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            # 如果提交数据合法，调用表单的 save 方法将用户数据保存到数据库
            form.save()

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ProfileForm( instance=request.user)

    return render(request, 'usercenter/profile.html', {'form': form})

users/templates/layout/uc.html
<!DOCTYPE html>
<html>

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}首页{% endblock %} - 云学院,免费云计算视频网站</title>
    <link href="//cdn.bootcss.com/aos/2.2.0/aos.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/united/bulmaswatch.min.css">
    <style>
        .main-nav {
            margin-bottom: 2rem
        }
    </style>
    <link rel="stylesheet" href="{% static 'admin.css' %}"> {% block style %}{% endblock %}
</head>

<body>
    <nav class="main-nav nav has-shadow">
        <div class="container">
            <div class="nav-left">
                <a class="nav-item" href="{% url 'index' %}">
                    <h1 class="title is-5">云学院</h1>
                </a>
                <a class="nav-item is-active" href="{% url 'index' %}">首页</a>
                <a class="nav-item is-active" href="{% url 'courses:index' %}">课程目录</a>
            </div>
            <span class="nav-toggle">
                <span></span>
                <span></span>
                <span></span>
            </span>
            <div class="nav-right nav-menu">
                <div class="nav-item">
                    <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                        <input class="input is-small" type="search" name="q" required placeholder="输入关键词并回车">

                    </form>

                </div>
                {% if user.is_authenticated %}
                <a class="nav-item" href="{% url 'users:uc_index'%}">
                    <span class="icon">
                        <i class="fa fa-user"></i>
                    </span>
                    {% if user.nickname %}
                    {{user.nickname}}
                    {% else %}
                    {{user.username}}
                    {% endif %}
                </a>
                <a class="nav-item" href="{% url 'logout' %}?next={{ request.path }}">
                    <span class="icon">
                        <i class="fa fa-sign-out"></i>
                    </span>

                </a>
                {% else %}
                <a class="nav-item" href="{% url 'login' %}?next={{ request.path }}">
                    <span class="icon">
                        <i class="fa fa-sign-in"></i>
                    </span>
                    登陆
                </a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="columns">
            <div class="column is-3">
                <aside class="menu">
                    <p class="menu-label">
                            个人中心
                    </p>
                    <ul class="menu-list">
                        <li>
                            <a href="{% url 'users:uc_index' %}">个人主页</a>
                        </li>
                        <li>
                            <a href="{% url 'users:uc_profile'%}">个人设置</a>
                        </li>
                        <li>
                            <a href="{% url 'password_change' %}?next={{ request.path }}">安全设置</a>
                        </li>
                        <li>
                            <a>第三方绑定</a>
                        </li>

                    </ul>
                    <p class="menu-label">
                        我的学习
                    </p>


                </aside>
            </div>
            <div class="column is-9">
                {% block content %} {% endblock %}
            </div>
        </div>
        <div class="is-clearfix">

        </div>
    </div>


    <footer class="footer">
        <div class="container">
            <div class="content has-text-centered">
                <p>
                    云学院 版权所有 © 2017-2018 · ICP备 XXXXXXXXX 号
                </p>
            </div>
        </div>
    </footer>
    {% block script %}{% endblock %}
</body>

</html>