courses/urls.py
from django.conf.urls import url

from .views import * 

urlpatterns = [
    url(r"^$",categoriesView,name="index"),
    url(r'^category/(?P<category_id>[0-9]+)',categoryView,name="category"),
    url(r'^series/(?P<series_id>[0-9]+)',seriesView,name="series"),
    url(r'^episode/(?P<episode_id>[0-9]+)',episodeView,name="episode"),
]

framework/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings

import courses.views as courses_view


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include('courses.urls',namespace="courses")),
    url(r'^search/', include('haystack.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$',courses_view.indexView,name="index"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^$',views.ucIndex,name="uc_index"),
    url(r'^profile/',views.ucProfile,name="uc_profile"),
]

courses/models.py
from django.db import models
from simplemde.fields import SimpleMDEField
import markdown
from django.utils.html import strip_tags
from django.conf import settings


""" 状态 """
STATUS_CHOICES = (
    ('d', '草稿'),
    ('p', '已发布'),
    ('w', '已删除'),
)

class Category(models.Model):
    title = models.CharField('标题',max_length=100)
    description = SimpleMDEField(verbose_name=u'描述')
    excerpt = models.CharField("摘要",max_length=200, blank=True)
    image = models.ImageField('图片',upload_to="pictures/%Y/%m/%d",help_text="比例为16:9")
    pub_date = models.DateTimeField('发布日期',auto_now_add=True)
    update_date = models.DateTimeField('更新日期',auto_now=True)
    sort = models.IntegerField("序号",default=99,help_text="序号越小越靠前")
    def save(self, *args, **kwargs):
        if not self.excerpt:
             md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
             self.excerpt = strip_tags(md.convert(self.description))[:54]
        super(Category, self).save(*args, **kwargs)
    def __unicode__(self):
        return self.title
    def __str__(self):
        return self.title
    class Meta:
        verbose_name = '目录'
        verbose_name_plural = '0-目录'
        ordering = ['sort']  # 按照哪个栏目排序
        get_latest_by = 'pub_date'

class Series(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    category = models.ForeignKey(Category)
    title = models.CharField('标题',max_length=100)
    description = SimpleMDEField(verbose_name=u'描述')
    excerpt = models.CharField("摘要",max_length=200, blank=True)
    image = models.ImageField('图片',upload_to="pictures/%Y/%m/%d",help_text="比例为16:9")
    pub_date = models.DateTimeField('发布日期',auto_now_add=True)
    update_date = models.DateTimeField('更新日期',auto_now=True)
    views = models.PositiveIntegerField(default=0)
    videolength = models.PositiveIntegerField(default=0)
    sort = models.IntegerField("序号",default=99,help_text="序号越小越靠前")
    status = models.CharField('状态',max_length=1, choices=STATUS_CHOICES,default='d')
    def save(self, *args, **kwargs):
        if not self.excerpt:
             md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
             self.excerpt = strip_tags(md.convert(self.description))[:54]
        super(Series, self).save(*args, **kwargs)
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])
    def addlength(self,length):
        self.videolength += length
        self.save(update_fields=['videolength'])
    def __unicode__(self):
        return self.title
    def __str__(self):
        return self.title
    class Meta:
        verbose_name = '课程'
        verbose_name_plural = '1-课程'
        ordering = ['sort']  # 按照哪个栏目排序
        get_latest_by = 'pub_date'

class Section(models.Model):
    category = models.ForeignKey(Category)
    series = models.ForeignKey(Series)
    title = models.CharField('标题',max_length=300)
    sort = models.IntegerField("序号",default=1,help_text="序号越小越靠前")
    pub_date = models.DateTimeField('发布日期',auto_now_add=True)
    update_date = models.DateTimeField('更新日期',auto_now=True)
    def save(self, *args, **kwargs):
        self.category_id = self.series.category_id
        super(Section, self).save(*args, **kwargs)
    def __str__(self):
        return self.title
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = '章节'
        verbose_name_plural = '2-章节'
        ordering = ['sort']  # 按照哪个栏目排序
        get_latest_by = 'pub_date'

class Episode(models.Model):
    category = models.ForeignKey(Category)
    series = models.ForeignKey(Series)
    section = models.ForeignKey(Section)
    title = models.CharField('标题',max_length=300)
    description = SimpleMDEField(verbose_name=u'描述')
    excerpt = models.CharField("摘要",max_length=200, blank=True)
    sort = models.IntegerField("序号",default=1,help_text="序号越小越靠前")
    video = models.FileField('附件文件',upload_to="wp-content/uploads/attachment/%Y/%m/%d")
    video_length = models.PositiveIntegerField("视频长度",help_text='以秒为单位')
    pub_date = models.DateTimeField('发布日期',auto_now_add=True)
    update_date = models.DateTimeField('更新日期',auto_now=True)
    status = models.CharField('状态',max_length=1, choices=STATUS_CHOICES,default='d')
    def save(self, *args, **kwargs):
       
        self.series = self.section.series
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.description))[:54]
            self.series.addlength(self.video_length)
       
        self.category = self.section.category
        super(Episode, self).save(*args, **kwargs)
    def __str__(self):
        return self.title
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = '小节'
        verbose_name_plural = '3-小节'
        ordering = ['sort','-pub_date']  # 按照哪个栏目排序
        get_latest_by = 'pub_date'

class Attachment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    category = models.ForeignKey(Category)
    series = models.ForeignKey(Series)
    title = models.CharField('标题',max_length=100)
    description = SimpleMDEField(verbose_name=u'描述')
    excerpt = models.CharField("摘要",max_length=200, blank=True)
    file = models.FileField('附件文件',upload_to="wp-content/uploads/attachment/%Y/%m/%d")
    sort = models.IntegerField("序号",default=1,help_text="序号越小越靠前")
    pub_date = models.DateTimeField('发布日期',auto_now_add=True)
    update_date = models.DateTimeField('更新日期',auto_now=True)
    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.description))[:54]
        self.category = self.series.category
        super(Attachment, self).save(*args, **kwargs)
    def __str__(self):
        return self.title
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = '附件'
        verbose_name_plural = '4-课程资料'
        ordering = ['sort','-pub_date']  # 按照哪个栏目排序
        get_latest_by = 'pub_date'
class Cite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    category = models.ForeignKey(Category)
    series = models.ForeignKey(Series)
    title = models.CharField('标题',max_length=100)
    description = SimpleMDEField(verbose_name=u'描述')
    excerpt = models.CharField("摘要",max_length=200, blank=True)
    link = models.URLField('链接')
    sort = models.IntegerField("序号",default=1,help_text="序号越小越靠前")
    pub_date = models.DateTimeField('发布日期',auto_now_add=True)
    update_date = models.DateTimeField('更新日期',auto_now=True)
    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.description))[:54]
        self.category = self.series.category
        super(Cite, self).save(*args, **kwargs)
    def __str__(self):
        return self.title
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = '延展阅读'
        verbose_name_plural = '5-延展阅读'
        ordering = ['sort','-pub_date']  # 按照哪个栏目排序
        get_latest_by = 'pub_date'

courses/views.py
from django.shortcuts import render
from .models import * 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def indexView(request):
    return render(request,"index.html")

def categoriesView(request):
    categories_list = Category.objects.all()

    paginator = Paginator(categories_list, 25) # Show 25 contacts per page

    page = request.GET.get('page')

    try:
        categories = paginator.page(page)
    except PageNotAnInteger :
        categories = paginator.page(1)
    except EmptyPage:
        categories = paginator.page(paginator.num_pages)

    return render(request,"category.html",{"categories":categories})

def categoryView(request,category_id):
    category = Category.objects.get(pk = category_id)
    category.description = markdown.markdown(category.description)
    series_list=  Series.objects.filter(category_id=category_id,status="p")
    paginator = Paginator(series_list, 25) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        series = paginator.page(page)
    except PageNotAnInteger :
        series = paginator.page(1)
    except EmptyPage:
        series = paginator.page(paginator.num_pages)

    return render(request,"series_list.html",{"series":series,"category":category})

def seriesView(request,series_id):
    series = Series.objects.get(pk = series_id)
    sections = Section.objects.filter(series_id = series_id)
    episodes = Episode.objects.filter(series_id = series_id,status="p")
    attachments = Attachment.objects.filter(series_id = series_id )
    cites = Cite.objects.filter(series_id = series_id )

    series.description = markdown.markdown(series.description,extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])
    return render(request,"series.html",{"series":series,
                                        "sections":sections,
                                        "episodes":episodes,
                                        "attachments":attachments,
                                        "cites":cites
                                        })                

def episodeView(request,episode_id):
    episode = Episode.objects.get(pk=episode_id)
    episode.description = markdown.markdown(episode.description,extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])
    return render(request,"episode.html",{"episode":episode})

courses/templates/category.html
{% extends 'layout/app.html' %} {% block content %}

<section class="container">
  <div class="columns">
    {% for category in categories %}
    <div class="column is-4 category-item">
      <div class="card">
        <div class="card-image">
          <a href="{% url 'courses:category' category.id %}">
            <figure class="image is-16by9">
              <img src="{{ category.image.url }}" alt="Placeholder image">
            </figure>
          </a>
        </div>
        <div class="card-content">
          <div class="content has-text-centered">
            <a href="{% url 'courses:category' category.id %}">
              <h1 class="title"> {{ category.title }}</h1>
            </a>
            <div class="columns">
              <div class="column is-4">
                <p class="subtitle">{{category.series_set.count}} 课程</p>
              </div>
              <div class="column is-4">
                <p class="subtitle">{{category.section_set.count}} 章节</p>
              </div>
              <div class="column is-4">
                  <p class="subtitle">{{category.episode_set.count}} 视频</p>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
</section>
<section class="container">
  <nav class="pagination is-centered" role="navigation" aria-label="pagination">

    <ul class="pagination-list">

      {% for page_number in categories.paginator.page_range %} {% ifequal page_number categories.number %}
      <a class="pagination-link is-current" aria-label="Page 1" aria-current="page"> {{ page_number }}</a>
      {% else %}
      <a href="?page={{ page_number }}" class="pagination-link" aria-label="Goto page {{ page_number }}">{{ page_number }}</a>
      {% endifequal %} {% endfor %}

    </ul>

  </nav>
</section>


{% endblock %} {% block style %}
<style>
  .category-item {
    padding-top: 20px;
    padding-bottom: 20px;
  }

  .pagination {
    padding-bottom: 20px;
  }
</style>

{% endblock%}

courses/templates/episode.html
{% extends 'layout/app.html' %} {% block content %}

<section class="container">
    <hr>
    <video class="video_player" controls>
        <source src="{{episode.video.url}}" type="video/mp4">
    </video>
    <h1 class="title">{{ episode.title }}</h1>
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="{% url 'index'%}">云学院</a>
            </li>
            <li>
                <a>{{episode.category.title}}</a>
            </li>
            <li>
                <a>{{episode.series.title}}</a>
            </li>
            <li class="is-active">
                <a>{{episode.title}}</a>
            </li>
        </ul>
    </nav>
    <h2 class="subtitle">小节内容介绍</h2>
    <div class="content">
        {{episode.description|safe}}
    </div>
    <h2 class="subtitle">讨论区</h2>

</section>

{% endblock %} 

{% block style%}
<link rel="stylesheet" href="https://cdnjs.cat.net/ajax/libs/plyr/2.0.9/plyr.css"> 
<style>
    h1.title{
        margin: 10px 0px;
    }
</style>
{% endblock%} 

{% block script %}

<script src="https://cdnjs.cat.net/ajax/libs/plyr/2.0.9/plyr.js"></script>
<script>
    options = {
        i18n: {
            restart: "重新播放",
            rewind: "向后 {seektime} 秒",
            play: "播放",
            pause: "暂停",
            forward: "向前 {seektime} 秒",
            buffered: "加载完成",
            currentTime: "当前时间",
            duration: "缓冲",
            volume: "音量",
            toggleMute: "静音",
            toggleCaptions: "字幕",
            toggleFullscreen: "全屏"
        },
        controls: ['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'fullscreen'],
        tooltips: { controls: true, seek: true }
    }
    plyr.setup('.video_player', options);
</script> {% endblock %}

courses/templates/index.html
{% extends 'layout/app.html' %} {% block content %}
<section class="banner has-text-centered">
  <div class="container">
    <svg viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" width="200" height="200">
      <defs>
        <style/>
      </defs>
      <path d="M971.928 323.9L523.792 121.562c-5.354-2.417-11.49-2.417-16.845 0L58.81 323.9c-7.33 3.31-12.043 10.608-12.043 18.652s4.712 15.342 12.044 18.653l21.476 9.695v323.93c0 11.304 9.162 20.467 20.466 20.467s20.466-9.163 20.466-20.466V389.38l95.555 43.145.02 362.097c0 6.925 3.5 13.38 9.305 17.156 86.094 56 186.124 85.597 289.273 85.597 103.155 0 203.188-29.602 289.285-85.606 5.806-3.777 9.307-10.232 9.307-17.157l.005-362.088 157.962-71.32c7.33-3.312 12.043-10.61 12.043-18.654s-4.714-15.34-12.045-18.65zm-198.9 459.463c-77.3 47.846-166.142 73.08-257.658 73.08-91.51 0-180.35-25.23-257.647-73.07l-.017-332.365 249.242 112.535c2.677 1.208 5.55 1.812 8.422 1.812s5.745-.605 8.422-1.812l249.24-112.535-.003 332.355zM515.37 522.433l-398.402-179.88L515.37 162.67l398.402 179.882-398.402 179.88z"
      />
    </svg>

    <h2 class="title is-2 animated bounceIn">
      云学院
    </h2>
    <h5 class="title sub-title is-5 animated fadeIn">最新最专业的精品云计算学习课程尽在这里！ </h5>
  </div>
</section>
<section class="container category">
  <h1 class="title is-4">类别 × 3</h1>
  <div class="columns  has-text-centered">
    <div class="column">
      <div class="circle animated bounceIn">
        <h1 class="title is-1 ">Theory</h1>
        <h4 class="title sub-title is-5">云计算理论</h4>
      </div>
    </div>
    <div class="column">
      <div class="circle animated bounceIn">
        <h1 class="title is-1 ">Practice</h1>
        <h4 class="title sub-title is-5">云计算实践</h4>
      </div>
    </div>
    <div class="column">
      <div class="circle animated bounceIn">
        <h1 class="title is-1 ">Coding</h1>
        <h4 class="title sub-title is-5">云计算编码</h4>
      </div>
    </div>
  </div>
</section>
<section class="style">
  <div class="container">

    <h1 class="title is-4">如何学习 × 4</h1>
    <div class="columns is-multiline">

      <div class="column is-6">
        <h3 class="title is-5  animated zoomIn">
          <i class="fa fa-check-circle" aria-hidden="true"></i> 理论与实践并重</h3>
        <p class="animated zoomIn">我们希望您能够在掌握技能的同时，了解其背后的理论，帮助您更好的使用云计算。享受云计算的红利</p>
      </div>
      <div class="column is-6">
        <h3 class="title is-5  animated zoomIn">
          <i class="fa fa-check-circle" aria-hidden="true"></i> 由浅入深，层层递进</h3>
        <p class="animated zoomIn">我们根据您的情况，为您定制了不同难度的学习课程，您可以根据课程进行学习，降低学习难度。</p>
      </div>
      <div class="column is-6">
        <h3 class="title is-5  animated zoomIn">
          <i class="fa fa-check-circle" aria-hidden="true"></i> 输出输出共举</h3>
        <p class="animated zoomIn">我们认为您的课程学习是在完成知识的输入过程，但是知识的输入并不意味着您已经完全学会了， 所以我们设计了知识输出的环节，从输入到输出，真正掌握知识。
        </p>
      </div>
      <div class="column is-6">
        <h3 class="title is-5  animated zoomIn">
          <i class="fa fa-check-circle" aria-hidden="true"></i> 课后即时交流</h3>
        <p class="animated zoomIn">根据不同的课程，我们建立了不同的社群，帮助您找到志同道合之人，共同学习，共同进步。</p>
      </div>

    </div>


  </div>
</section>
<section class="faq container">
  <h1 class="title is-4">FAQ × 6</h1>
  <div class="columns">

    <div class="column is-4 has-text-right">
      <h3 class="title is-5">
        为什么是云学院？
      </h3>
      <h3 class="title is-5">
        在这里我能学到什么？
      </h3>
      <h3 class="title is-5">
        适合我学习么？
      </h3>
    </div>

    <div class="column is-8">
      <div class="player aos-init aos-animate" data-aos="fade-down">
        视频框
      </div>

    </div>

  </div>
</section>
<section class="coureses">
  <div class="container">
    <h1 class="title is-4">最新教程 × 9</h1>

    <ul class="columns is-multiline">


      <li class="column is-4">
        <a class="course-name link" href="/course/functional-programer">
          函数式编程
        </a>
        <span class="course-type vip"> 会员课程 </span>
        <p>了解一下函数式编程的范式，学会并掌握它，可以让你的视野更开拓。</p>
      </li>

    </ul>
  </div>
</section>
<div class="count">
  <div class="container">
    <h4 class="title is-4">统计 × 4 </h4>
    <div class="level">
      <div class="level-item has-text-centered">
        <div data-aos="zoom-in" class="aos-init aos-animate">
          <p class="heading">课程量</p>
          <p class="title">70</p>
        </div>
      </div>

    </div>

  </div>
</div>
</section>
<div class="tags">

  <div class="container">
    <h4 class="title is-4">课程体系 × N</h4>
    <div class="columns is-multiline aos-init aos-animate" data-aos="zoom-out">
      <div class="column is-3 has-text-centered">
        <h3>AWS</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>Azure</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>阿里云</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>腾讯云</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>百度云</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>网易云</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>UCloud</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>QingCloud</h3>
      </div>

      <div class="column is-3 has-text-centered">
        <h3>Digital Ocean</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>Linode</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>LeanCloud</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>Heroku</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>Django</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>Think.js</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>Laravel</h3>
      </div>
      <div class="column is-3 has-text-centered">
        <h3>Beego</h3>
      </div>
    </div>
    <p style="text-align: center;font-size: 14px; color: #333;margin-top: 25px;">内容还在持续增长...</p>

  </div>
</div>
{% endblock %} {% block style %}
<link rel="stylesheet" href="https://fonts.cat.net/css?family=Fira+Mono">
<style type="text/css">
  body {
    background-color: #f5f5f5;
  }

  .category,
  .banner,
  .style,
  .faq,
  .count,
  .tags,
  .coureses {
    padding: 50px 0px;
  }

  .banner,
  .coureses,
  .style,
  .tags {
    background-color: #fff;

  }

  .tags .column h3 {
    font-size: 28px;
    margin: 20px 0;
    font-family: "Fira Mono";
  }

  .category .title {
    font-family: "Fira Mono";
  }
</style>

{% endblock %}

courses/templates/series.html
{% extends 'layout/app.html' %} 
{% load time_extra %}
{% block content %}

<section class="hero is-link">
    <div class="hero-body">
        <div class="container">
            <div class="columns has-text-centered">
                <div class="column is-12">
                    <p class="title">
                        {{series.title}}
                    </p>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>

<section class="content container">
    <div class="columns">
        <div class="column is-8">
            <div>
                <!-- description -->
                <h1 id="description" class="title is-12">课程介绍</h1>
                <hr>
                <div class="content">
                    {{series.description|safe}}
                </div>
                <br>
                <!-- attribute -->
                <h1 id="attribute" class="title is-12">课程介绍</h1>
                <hr>
                <div class="columns">
                    <div class="column">
                        <p>课程所属目录：{{ series.category }}</p>
                    </div>
                    <div class="column">
                        <p>视频数：{{series.episode_set.count}}</p>
                    </div>
                    <div class="column">
                        <p>总时长：{{ series.videolength|time_format}}</p>
                    </div>
                </div>
                <br>
                <!-- video list -->
                <h1 id="videolist" class="title is-12">课程列表</h1>
                <hr>
                <ul>
                    {% for item in sections %}
                    <li class="section-item">
                        <p class="subtitle">
                            <span class="tag is-black">{{forloop.counter}}</span> {{item.title}}</p>
                        <ul>
                            {% for o in episodes %} {% if o.section_id == item.id %}
                            <li class="episode-item">
                                <a href="{% url 'courses:episode' o.id %}">
                                    <span class="tag is-primary">{{forloop.counter}}</span> {{o.title}}</a>  <span class="has-text-right has-text-grey is-pulled-right	">{{ o.video_length|time_format }}</span>  - <small>{{o.excerpt}}</small>
                            </li>
                            {% endif %} {% endfor %}
                        </ul>
                        <hr>
                    </li>
                    {% endfor %}
                </ul>
                <br>
                <!-- file list -->
                <h1 id="filelist" class="title is-12">附件下载</h1>
                <hr>
                <ul>
                
                {% for item in attachments %}
                        <li><span class="tag is-primary"> {{forloop.counter}} </span> <a href="{{item.file.url}}">{{item.title}}</a>- <small>{{item.excerpt}}</small></li>
                {% endfor %}
                    
                </ul>
                 <!-- cite list -->
                 <h1 id="linklist" class="title is-12">相关链接</h1>
                 <hr>
                 <ul>
                 
                 {% for item in cites %}
                         <li><span class="tag is-primary"> {{forloop.counter}} </span> <a href="{{item.link}}">{{item.title}}</a>- <small>{{item.excerpt}}</small></li>
                 {% endfor %}
                     
                 </ul>
            </div>
        </div>
        <div class="column is-4 is-hidden-mobile">
            <aside class="menu">
                <p class="menu-label">
                    课程介绍
                </p>
                <ul class="menu-list">
                    <li>
                        <a href="#description">课程介绍</a>
                    </li>
                    <li>
                        <a href="#attribute">课程属性</a>
                    </li>
                </ul>
                <p class="menu-label">
                    学习资源
                </p>
                <ul class="menu-list">
                    <li>
                        <a href="#videolist">课程列表</a>
                    </li>
                    <li>
                        <a href="#filelist">附件下载</a>
                    </li>
                    <li>
                        <a href="#linklist">相关链接</a>
                    </li>
                </ul>
            </aside>


        </div>

    </div>



</section>

{%endblock%} {% block style %}

<style>
    li {
        list-style: none;
    }

    .section-item {
        padding: 10px 0px;
    }

    .episode-item {
        padding: 5px 0px;
    }
</style>

{% endblock %}

courses/templates/series_list.html
{% extends 'layout/app.html' %} {% load time_extra %} {% block content %}
<section class="hero is-primary">

    <!-- Hero content: will be in the middle -->
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                {{category.title}}
            </h1>
            <p>
                {{category.description|safe}}
            </p>

        </div>
    </div>
</section>
<section class="container">
    <div class="columns">
        {% for item in series %}
        <div class="column is-4 category-item">
            <div class="card">
                <div class="card-image">
                    <figure class="image is-16by9">
                        <a href="{% url 'courses:series' item.id%}">
                            <img src="{{ item.image.url }}" alt="Placeholder image">
                        </a>
                    </figure>
                </div>
                <div class="card-content">
                    <div class="content has-text-centered">
                        <a href="{% url 'courses:series' item.id%}">
                            <h1 class="title"> {{ item.title }}</h1>
                        </a>

                        <div class="columns">

                            <div class="column is-6">
                                <p class="subtitle">{{item.section_set.count}} 章节</p>
                            </div>
                            <div class="column is-6">
                                <p class="subtitle">{{item.episode_set.count}} 视频</p>
                            </div>
                           
                        </div>
                        <div class="columns">
                                <div class="column ">
                                        <p class="subtitle">总时长：{{item.videolength|time_format}} </p>
                                </div>
                        </div>
                        <p>{{item.excerpt}}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</section>
<section class="container">
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">

        <ul class="pagination-list">

            {% for page_number in series.paginator.page_range %} {% ifequal page_number series.number %}
            <a class="pagination-link is-current" aria-label="Page 1" aria-current="page"> {{ page_number }}</a>
            {% else %}
            <a href="?page={{ page_number }}" class="pagination-link" aria-label="Goto page {{ page_number }}">{{ page_number }}</a>
            {% endifequal %} {% endfor %}

        </ul>

    </nav>
</section>

{% endblock %} {% block style%}
<style>
    .category-item {
        padding-top: 20px;
        padding-bottom: 20px;
    }

    .pagination {
        padding-bottom: 20px;
    }
</style>
{% endblock %}