framework/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings

import courses.views as courses_view


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include('courses.urls',namespace="courses")),
    url(r'^search/', include('haystack.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$',courses_view.indexView,name="index"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^$',views.ucIndex,name="uc_index"),
    url(r'^profile/',views.ucProfile,name="uc_profile"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    nickname = models.CharField("昵称",max_length=50, blank=True)
    bio = models.TextField("个人介绍",blank=True)
    website = models.URLField("网站地址",help_text="粘贴您的网站链接至此",blank=True)
    github = models.URLField("Github 地址",help_text="粘贴您的个人页面链接至此",blank=True)
    weibo = models.URLField("微博地址",help_text="粘贴您的微博至此",blank=True)
    class Meta(AbstractUser.Meta):
        pass

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

from django.forms import ModelForm


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")
class ProfileForm(ModelForm):
    class Meta:
        model = User
        fields = ['nickname','bio','website','github','weibo']

users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, ProfileForm
from .models import User


def register(request):
    # todo 处理 next 的安全性
    # 从 get 或者 post 请求中获取 next 参数值
    # get 请求中，next 通过 url 传递，即 /?next=value
    # post 请求中，next 通过表单传递，即 <input type="hidden" name="next" value="{{ next }}"/>
    redirect_to = request.POST.get('next', request.GET.get('next', ''))

    # 只有当请求为 POST 时，才表示用户提交了注册信息
    if request.method == 'POST':
        # request.POST 是一个类字典数据结构，记录了用户提交的注册信息
        # 这里提交的就是用户名（username）、密码（password）、确认密码、邮箱（email）
        # 用这些数据实例化一个用户注册表单
        form = RegisterForm(request.POST)

        # 验证数据的合法性
        if form.is_valid():
            # 如果提交数据合法，调用表单的 save 方法将用户数据保存到数据库
            form.save()

            if redirect_to:
                return redirect(redirect_to)
            else:
                return redirect('/')
    else:
        # 请求不是 POST，表明用户正在访问注册页面，展示一个空的注册表单给用户
        form = RegisterForm()

    # 渲染模板
    # 如果用户正在访问注册页面，则渲染的是一个空的注册表单
    # 如果用户通过表单提交注册信息，但是数据验证不合法，则渲染的是一个带有错误信息的表单
    # 将记录用户注册前页面的 redirect_to 传给模板，以维持 next 参数在整个注册流程中的传递
    return render(request, 'users/register.html', context={'form': form, 'next': redirect_to})


def ucIndex(request):
    return render(request, "usercenter/index.html")


def ucProfile(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            # 如果提交数据合法，调用表单的 save 方法将用户数据保存到数据库
            form.save()

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ProfileForm( instance=request.user)

    return render(request, 'usercenter/profile.html', {'form': form})

users/templates/users/register.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>注册 - 云学院</title>
  <link href="//cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/united/bulmaswatch.min.css">  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
  {% load staticfiles %}   
  <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">
</head>
<body>
  <section class="hero is-success is-fullheight">
    <div class="hero-body">
      <div class="container has-text-centered">
        <div class="column is-6 is-offset-3">
          <h3 class="title has-text-grey">注册</h3>
          <p class="subtitle has-text-grey">👥 从今天开始我们相知相遇。</p>
          <div class="box">
            <figure class="avatar">
              <img src="https://ws3.sinaimg.cn/large/006tKfTcgy1fkywyrh5nfj30b40b40sm.jpg" width="128">
            </figure>
            {% load socialaccount %}
            
            <div class="columns">
              <div class="column">
                  <a class="button is-primary is-large" href="{% provider_login_url "github" %}">Github注册</a>
              </div>
            </div>
            <hr>
            <form class="form" action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            
             <div class="field">
                    <div class="control">
                    {% if field.name != 'password1' and field.name != 'password2' %}
                      <input name="{{ field.name }}" class="input is-large" type="text" placeholder="{{ field.label }}">
                    {% else %}
                    <input name="{{ field.name }}" class="input is-large" type="password" placeholder="{{ field.label }}">
                    
                    {% endif %}
                    </div>
                  </div>
                {{ field.errors }}
                {% if field.help_text %}
                    <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                {% endif %}
            {% endfor %}
            <input type="hidden" name="next" value="{{ next }}"/>
              <button type="submit" class="button is-block is-info is-large">注册</button>
            </form>
          </div>
          <p class="has-text-grey">
            <a href="{% url 'login' %}">登陆</a> &nbsp;·&nbsp;
            <a href="{% url 'password_reset' %}">忘记密码</a> 
          </p>
        </div>
      </div>
    </div>
  </section>
</body>
</html>